apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: core-services
type: Opaque
stringData:
  keycloak-admin-user: projex_root
  keycloak-admin-password: ProjexAdminPassword2026! # 👈 Senha master de segurança do painel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: core-services
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0-alpine # Versão estável e ultra leve
        args: ["start-dev"] # Modo otimizado para o nosso laboratório custo zero
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloak-admin-user
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: keycloak-admin-password
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: core-services
spec:
  type: ClusterIP # Mantém o Keycloak protegido internamente
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak
