apiVersion: v1
data:
  keycloak-admin-password: dXNlcjEyMw==
  keycloak-admin-user: YWRtaW4=
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: projex-enterprise-apps:/Secret:core-services/keycloak-secret
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"keycloak-admin-password":"dXNlcjEyMw==","keycloak-admin-user":"YWRtaW4="},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"projex-enterprise-apps:/Secret:core-services/keycloak-secret"},"name":"keycloak-secret","namespace":"core-services"},"type":"Opaque"}
  name: keycloak-secret
  namespace: core-services
type: Opaque
