apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: core-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: "mudar123"
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: core-services
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
